### ISSUE TITLE
Correct JDBC syntax for mysql

### ISSUE THREAD

**Issue by robthompsonweb** [hasura/ndc-jvm-mono#21]
I am unable to get the Mysql connector to work (postgress and mongodb work fine)

is this the correct JDBC format?
`APP_MYSQL_JDBC_URL="jdbc:mysql://root:password@local.hasura.dev:3308/chronomics_local"`

Not sure if the first error has anything to do with it, or its just a warning.

```
hasura (main)$ ddn connector introspect mysql     
2:41PM INF Using Subgraph config file "app/subgraph.yaml" found in context.
2:41PM INF Using localEnvFile ".env" found in context.
java.nio.Bits#unaligned() check failed.Unsafe based read/write of primitive types won't be used
java.lang.reflect.InaccessibleObjectException: Unable to make static boolean java.nio.Bits.unaligned() accessible: module java.base does not "opens java.nio" to unnamed module @68530210
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:197)
	at org.apache.hadoop.hbase.unsafe.HBasePlatformDependent.checkUnaligned(HBasePlatformDependent.java:176)
	at org.apache.hadoop.hbase.unsafe.HBasePlatformDependent.<clinit>(HBasePlatformDependent.java:49)
	at org.apache.hadoop.hbase.util.Bytes.<clinit>(Bytes.java:130)
	at org.apache.phoenix.util.ByteUtil.<clinit>(ByteUtil.java:92)
	at org.apache.phoenix.schema.types.PDataType.<clinit>(PDataType.java:507)
	at org.apache.phoenix.monitoring.MetricType.<clinit>(MetricType.java:30)
	at org.apache.phoenix.monitoring.GlobalClientMetrics.<clinit>(GlobalClientMetrics.java:101)
	at org.apache.phoenix.jdbc.PhoenixDriver.connect(PhoenixDriver.java:221)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at org.jooq.impl.DSL.using(DSL.java:573)
	at io.hasura.cli.MySQLConfigGenerator.getConfig(MySQLConfigGenerator.kt:18)
	at io.hasura.cli.CLI.update(main.kt:70)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.hasura.cli.CLI$Companion.main(main.kt:98)
	at io.hasura.cli.CLI.main(main.kt)
Cannot locate configuration: tried hadoop-metrics2-phoenix.properties,hadoop-metrics2.properties
org.jooq.exception.DataAccessException: SQL [Error when initialising Connection]; Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.jooq.impl.Tools.translate(Tools.java:3572)
	at org.jooq.impl.Tools.translate(Tools.java:3560)
	at org.jooq.impl.DSL.using(DSL.java:577)
	at io.hasura.cli.MySQLConfigGenerator.getConfig(MySQLConfigGenerator.kt:18)
	at io.hasura.cli.CLI.update(main.kt:70)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.hasura.cli.CLI$Companion.main(main.kt:98)
	at io.hasura.cli.CLI.main(main.kt)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
```

**Comment by GavinRay97** [comment]
Please try passing the USER and PASSWORD as connection string properties, an example being here:
https://github.com/hasura/ndc-jvm-mono/blob/084bde9aac2e42c2782b110e15b82ef4bd473b79/docker-compose.yaml#L57

**Comment by HighLiuk** [comment]
Still does not work as of 2025.

This works:
```
mysql -u root -proot -h 127.0.0.1 -P 10004 local
```

but this does not:
```
JDBC_URL="jdbc:mysql://127.0.0.1:10004/local?user=root&password=root"
```

<details><summary>Error Message</summary>

```
11:28AM INF Using Subgraph config file "app/subgraph.yaml" found in context.
11:28AM INF Using localEnvFile ".env" found in context.
No existing configuration file found at /etc/connector/configuration.json
Introspecting database...
org.jooq.exception.DataAccessException: SQL [Error when initialising Connection]; Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at org.jooq.impl.Tools.translate(Tools.java:3572)
        at org.jooq.impl.Tools.translate(Tools.java:3560)
        at org.jooq.impl.DSL.using(DSL.java:577)
        at io.hasura.cli.MySQLConfigGenerator.generateConfig(MySQLConfigGenerator.kt:25)
        at io.hasura.cli.CLI.update(main.kt:127)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.hasura.cli.CLI$Companion.main(main.kt:145)
        at io.hasura.cli.CLI.main(main.kt)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:837)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
        at org.jooq.impl.DSL.using(DSL.java:573)
        ... 14 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:142)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:961)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
        ... 20 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:589)
        at java.base/sun.nio.ch.Net.connect(Net.java:578)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:751)
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53)
        ... 23 more
11:28AM ERR introspect failed with error: exit status 1
```

</details>
